
const D=window.WEEK1, P='sl_v11_'; const $=id=>document.getElementById(id);
function key(id){return P+id}
function save(el){if(!el.dataset.id)return;localStorage.setItem(key(el.dataset.id),el.type==='checkbox'?String(el.checked):el.value);progress()}
function restore(){document.querySelectorAll('[data-id]').forEach(el=>{let v=localStorage.getItem(key(el.dataset.id));if(v!==null){if(el.type==='checkbox')el.checked=v==='true';else el.value=v}});progress()}
function progress(){let c=[...document.querySelectorAll('input[type=checkbox][data-id]')],d=c.filter(x=>x.checked).length,p=c.length?Math.round(d/c.length*100):0;if($('progressbar'))$('progressbar').style.width=p+'%';if($('progressText'))$('progressText').textContent=p+'% erledigt'}
function screen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('visible'));$(id).classList.add('visible');document.querySelectorAll('[data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'})}
function days(){ $('daysContainer').innerHTML=D.days.map((x,i)=>`<div class=card><h2>${x.name}</h2><span class=badge>${x.focus}</span><p class=small>${x.info}</p><h3>Ernährung</h3>${x.meals.map((m,j)=>`<div class=meal-card><div class=meal-top><div><div class=meal-title>${m[1]}</div><div class=meal-meta>${m[0]}</div></div><input type=checkbox data-id="meal_${i}_${j}"></div><p>${m[2]}</p>${m[3]?`<p class=small>${m[3]}</p>`:''}</div>`).join('')}<h3>Tagesziele</h3><label class=item><input type=checkbox data-id="day_${i}_protein">Proteinziel erreicht</label><label class=item><input type=checkbox data-id="day_${i}_water">Wasserziel erreicht</label><label class=item><input type=checkbox data-id="day_${i}_steps">Schritte erreicht</label><h3>Notizen</h3><textarea rows=3 data-id="day_note_${i}" placeholder="Wie lief der Tag?"></textarea></div>`).join('')}
function workouts(){ $('workoutContainer').innerHTML=D.workouts.map((w,wi)=>`<div class=card><h2>${w.title}</h2><span class=badge>${w.focus}</span><div class=note><b>Technik-Cues:</b> ${w.cues}</div>${w.exercises.map((e,ei)=>`<div class=exercise-card><div class=exercise-head><span class=exercise-title>${e[0]}</span><label><input type=checkbox data-id="ex_done_${wi}_${ei}"> erledigt</label></div><div class=exercise-meta><div><b>${e[1]}</b>Sätze</div><div><b>${e[2]}</b>Wdh.</div><div><b>${e[3]}</b>Pause</div><div><b>${e[5]}</b>RPE</div></div><div class=journal-grid><input type=text data-id="ex_weight_${wi}_${ei}" placeholder="Gewicht"><input type=text data-id="ex_rpe_${wi}_${ei}" placeholder="RPE tatsächlich"></div><textarea rows=2 data-id="ex_note_${wi}_${ei}" placeholder="Notizen"></textarea></div>`).join('')}<h3>Training heute</h3><div class=journal-grid><input type=text data-id="duration_${wi}" placeholder="Trainingsdauer"><input type=text data-id="avg_rpe_${wi}" placeholder="Ø RPE"></div><label class=item><input type=checkbox data-id="increase_${wi}">Nächstes Training Gewicht erhöhen?</label></div>`).join('')}
function recipes(){ $('recipeContainer').innerHTML=D.recipes.map((r,i)=>`<div class=recipe-card><div class=recipe-head><h2>Rezept ${i+1}</h2><span class=badge>${r[2]}</span></div><h3>${r[0]}</h3><div class=grid><div class=pill>${r[1]}</div><div class=pill>${r[3]}</div></div><h4>Zutaten</h4><ul>${r[4].map(z=>`<li>${z}</li>`).join('')}</ul><h4>Zubereitung</h4><p>${r[5]}</p><h4>Nährwerte</h4><p class=pill>${r[6]}</p><h4>Kinderfreundlich</h4><p class=small>Mild würzen, Komponenten bei Bedarf getrennt servieren.</p></div>`).join('')}
function shop(){ $('shopContainer').innerHTML=Object.entries(D.shopCats).map(([cat,items],ci)=>`<h3>${cat}</h3>${items.map((it,ii)=>`<label class=item><input type=checkbox data-id="shop_${ci}_${ii}"><span>${it}</span></label>`).join('')}`).join('')}
document.addEventListener('DOMContentLoaded',()=>{days();workouts();recipes();shop();restore();document.querySelectorAll('[data-screen]').forEach(b=>b.addEventListener('click',()=>screen(b.dataset.screen)));document.addEventListener('input',e=>save(e.target));document.addEventListener('change',e=>save(e.target));if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})});
