
const D=window.WEEK1, P='sl_v12_'; const $=id=>document.getElementById(id);
function key(id){return P+id}
function save(el){if(!el.dataset.id)return;localStorage.setItem(key(el.dataset.id),el.type==='checkbox'?String(el.checked):el.value);progress()}
function restore(){document.querySelectorAll('[data-id]').forEach(el=>{let v=localStorage.getItem(key(el.dataset.id));if(v!==null){if(el.type==='checkbox')el.checked=v==='true';else el.value=v}});progress()}
function progress(){let c=[...document.querySelectorAll('input[type=checkbox][data-id]')],d=c.filter(x=>x.checked).length,p=c.length?Math.round(d/c.length*100):0;if($('progressbar'))$('progressbar').style.width=p+'%';if($('progressText'))$('progressText').textContent=p+'% erledigt'}
function screen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('visible'));$(id).classList.add('visible');document.querySelectorAll('[data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'})}
function goRecipe(anchor){screen('rezepte');setTimeout(()=>{let el=$(anchor); if(el) el.scrollIntoView({behavior:'smooth',block:'start'});},100)}
window.goRecipe=goRecipe;
function days(){ $('daysContainer').innerHTML=D.days.map((x,i)=>`<div class=card><h2>${x.name}</h2><span class=badge>${x.focus}</span><p class=small>${x.info}</p><h3>Ernährung</h3>${x.meals.map((m,j)=>`<div class=meal-card><div class=meal-top><div><div class=meal-title>${m[3]?`<button class=recipe-link onclick="goRecipe('${m[3]}')">${m[2]}</button>`:m[2]}</div><div class=meal-meta>${m[0]} · ${m[1]}</div></div><input type=checkbox data-id="meal_${i}_${j}"></div>${m[4]?`<p class=small>${m[4]}</p>`:''}</div>`).join('')}<h3>Tagesziele</h3><label class=item><input type=checkbox data-id="day_${i}_protein">Proteinziel erreicht</label><label class=item><input type=checkbox data-id="day_${i}_water">Wasserziel erreicht</label><label class=item><input type=checkbox data-id="day_${i}_steps">Schritte erreicht</label><h3>Notizen</h3><textarea rows=3 data-id="day_note_${i}" placeholder="Wie lief der Tag?"></textarea></div>`).join('')}
function warmup(w,wi){return `<details><summary>Warm-up auswählen</summary><div class=grid><div><h4>Cardio</h4>${w.warmup.cardio.map((x,i)=>`<label class=item><input type=checkbox data-id="wu_${wi}_c_${i}">${x}</label>`).join('')}</div><div><h4>Mobility</h4>${w.warmup.mobility.map((x,i)=>`<label class=item><input type=checkbox data-id="wu_${wi}_m_${i}">${x}</label>`).join('')}</div><div><h4>Aktivierung</h4>${w.warmup.activation.map((x,i)=>`<label class=item><input type=checkbox data-id="wu_${wi}_a_${i}">${x}</label>`).join('')}</div></div></details>`}
function rpeBox(){return `<details><summary>RPE kurz erklärt</summary><p><b>RPE 10</b>: keine Wiederholung mehr möglich<br><b>RPE 9</b>: noch 1 Wdh. möglich<br><b>RPE 8</b>: noch 2 Wdh. möglich<br><b>RPE 7</b>: noch 3 Wdh. möglich</p><p class=small>Woche 1 liegt überwiegend bei RPE 7–8.</p></details>`}
function specialNote(name){ if(name==='Face Pull')return `<div class=note><b>Face Pull:</b> Seil etwa auf Stirnhöhe einstellen. Leicht versetzt stehen, Brust aufrichten, Ellbogen nach außen führen und Hände neben die Ohren ziehen. Nicht nach unten ziehen und nicht ins Hohlkreuz fallen.</div>`; if(name==='Farmer Carry')return `<div class=note><b>Farmer Carry:</b> Als Strecke/Zeit ausführen: 30 m oder ca. 45 Sek. Aufrecht bleiben, Schultern ruhig, Rumpf fest.</div>`; return ''}
function setRows(e,wi,ei){let sets=parseInt(e[1])||3,target=e[2];return `<table class=set-table><tr><th>Satz</th><th>Ziel</th><th>Gewicht</th><th>Wdh.</th><th>RPE</th><th>✓</th></tr>${Array.from({length:sets}).map((_,si)=>`<tr><td>${si+1}</td><td>${target}</td><td><input type=text data-id="set_w_${wi}_${ei}_${si}" placeholder="kg"></td><td><input type=text data-id="set_r_${wi}_${ei}_${si}" placeholder="Ist"></td><td><input type=text data-id="set_p_${wi}_${ei}_${si}" placeholder="RPE"></td><td><input type=checkbox data-id="set_d_${wi}_${ei}_${si}"></td></tr>`).join('')}</table>`}
function workouts(){ $('workoutContainer').innerHTML=D.workouts.map((w,wi)=>`<div class=card><h2>${w.title}</h2><div class=grid><div class=metric><span>Dauer</span>${w.duration}</div><div class=metric><span>Fokus</span>${w.focus}</div></div>${warmup(w,wi)}${rpeBox()}<div class=note><b>Technik-Cues:</b> ${w.cues}</div>${w.exercises.map((e,ei)=>`<div class=exercise-card><div class=exercise-head><span class=exercise-title>${e[0]}</span><label><input type=checkbox data-id="ex_done_${wi}_${ei}"> erledigt</label></div><div class=image-placeholder>Übungsbild: ${e[0]}<br><span class=small>Platzhalter für die Illustration</span></div><div class=exercise-meta><div><b>${e[1]}</b>Sätze</div><div><b>${e[2]}</b>Ziel-Wdh.</div><div><b>${e[3]}</b>Pause</div><div><b>${e[5]}</b>Ziel-RPE</div></div>${specialNote(e[0])}${setRows(e,wi,ei)}<textarea rows=2 data-id="ex_note_${wi}_${ei}" placeholder="Notizen"></textarea></div>`).join('')}<h3>Training heute</h3><div class=grid><input type=text data-id="duration_${wi}" placeholder="Trainingsdauer"><input type=text data-id="avg_rpe_${wi}" placeholder="Ø RPE"></div><label class=item><input type=checkbox data-id="increase_${wi}">Nächstes Training Gewicht erhöhen?</label></div>`).join('')}
function recipes(list=D.recipes){ $('recipeContainer').innerHTML=list.map((r)=>{let i=D.recipes.indexOf(r);return `<div class=recipe-card id="recipe-${i}"><div class=recipe-head><h2>Rezept ${i+1}</h2><span class=badge>${r[2]}</span></div><h3>${r[0]}</h3><div class=grid><div class=pill>${r[1]}</div><div class=pill>${r[3]}</div><div class=pill>${r[7]}</div></div><h4>Zutaten</h4><ul>${r[4].map(z=>`<li>${z}</li>`).join('')}</ul><h4>Zubereitung</h4><p>${r[5]}</p><h4>Nährwerte</h4><p class=pill>${r[6]}</p><h4>Kinderfreundlich</h4><p class=small>Mild würzen, Komponenten bei Bedarf getrennt servieren.</p></div>`}).join('')}
function shop(){ $('shopContainer').innerHTML=Object.entries(D.shopCats).map(([cat,items],ci)=>`<h3>${cat}</h3>${items.map((it,ii)=>`<label class=item><input type=checkbox data-id="shop_${ci}_${ii}"><span>${it}</span></label>`).join('')}`).join('')}
function filterRecipes(){let q=$('recipeSearch').value.toLowerCase().trim();let filtered=D.recipes.filter(r=>(r[0]+" "+r[3]+" "+r[7]+" "+r[4].join(" ")).toLowerCase().includes(q));recipes(filtered)}
document.addEventListener('DOMContentLoaded',()=>{days();workouts();recipes();shop();restore();document.querySelectorAll('[data-screen]').forEach(b=>b.addEventListener('click',()=>screen(b.dataset.screen)));document.addEventListener('input',e=>{save(e.target); if(e.target.id==='recipeSearch')filterRecipes()});document.addEventListener('change',e=>save(e.target));if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})});
