const D = window.WEEK1;
const PREFIX = "sl_v12_fixed_";
const $ = id => document.getElementById(id);
function storageKey(id){ return PREFIX + id; }
function save(el){ if(!el.dataset.id) return; localStorage.setItem(storageKey(el.dataset.id), el.type === "checkbox" ? String(el.checked) : el.value); updateProgress(); }
function restore(){ document.querySelectorAll("[data-id]").forEach(el => { const value = localStorage.getItem(storageKey(el.dataset.id)); if(value !== null){ if(el.type === "checkbox") el.checked = value === "true"; else el.value = value; } }); updateProgress(); }
function updateProgress(){ const checks = [...document.querySelectorAll('input[type="checkbox"][data-id]')]; const done = checks.filter(x => x.checked).length; const pct = checks.length ? Math.round(done / checks.length * 100) : 0; if($("progressbar")) $("progressbar").style.width = pct + "%"; if($("progressText")) $("progressText").textContent = pct + "% erledigt"; }
function showScreen(id){ document.querySelectorAll(".screen").forEach(s => s.classList.remove("visible")); $(id).classList.add("visible"); document.querySelectorAll("[data-screen]").forEach(b => b.classList.toggle("active", b.dataset.screen === id)); window.scrollTo({top:0, behavior:"smooth"}); }
function goRecipe(anchor){ showScreen("rezepte"); setTimeout(() => { const el = document.getElementById(anchor); if(el) el.scrollIntoView({behavior:"smooth", block:"start"}); }, 120); }
window.goRecipe = goRecipe;
function renderDays(){ $("daysContainer").innerHTML = D.days.map((day,i) => `<div class="card"><h2>${day.name}</h2><span class="badge">${day.focus}</span><p class="small">${day.info}</p><h3>Ernährung</h3>${day.meals.map((m,j) => `<div class="meal-card"><div class="meal-top"><div><div class="meal-title">${m[3] ? `<button class="recipe-link" onclick="goRecipe('${m[3]}')">${m[2]}</button>` : m[2]}</div><div class="meal-meta">${m[0]} · ${m[1]}</div></div><input type="checkbox" data-id="meal_${i}_${j}"></div>${m[4] ? `<p class="small">${m[4]}</p>` : ""}</div>`).join("")}<h3>Tagesziele</h3><label class="item"><input type="checkbox" data-id="day_${i}_protein">Proteinziel erreicht</label><label class="item"><input type="checkbox" data-id="day_${i}_water">Wasserziel erreicht</label><label class="item"><input type="checkbox" data-id="day_${i}_steps">Schritte erreicht</label><h3>Notizen</h3><textarea rows="3" data-id="day_note_${i}" placeholder="Wie lief der Tag?"></textarea></div>`).join(""); }
function renderWarmup(workout, wi){ return `<details><summary>Warm-up auswählen</summary><div class="grid"><div><h4>Cardio</h4>${workout.warmup.cardio.map((x,i) => `<label class="item"><input type="checkbox" data-id="wu_${wi}_c_${i}">${x}</label>`).join("")}</div><div><h4>Mobility</h4>${workout.warmup.mobility.map((x,i) => `<label class="item"><input type="checkbox" data-id="wu_${wi}_m_${i}">${x}</label>`).join("")}</div><div><h4>Aktivierung</h4>${workout.warmup.activation.map((x,i) => `<label class="item"><input type="checkbox" data-id="wu_${wi}_a_${i}">${x}</label>`).join("")}</div></div></details>`; }
function rpeBox(){ return `<details><summary>RPE kurz erklärt</summary><p><b>RPE 10</b>: keine Wiederholung mehr möglich<br><b>RPE 9</b>: noch 1 Wiederholung möglich<br><b>RPE 8</b>: noch 2 Wiederholungen möglich<br><b>RPE 7</b>: noch 3 Wiederholungen möglich</p><p class="small">Woche 1 liegt überwiegend bei RPE 7–8.</p></details>`; }
function specialNote(name){ if(name === "Face Pull") return `<div class="note"><b>Face Pull:</b> Seil etwa auf Stirnhöhe einstellen. Leicht versetzt stehen, Brust aufrichten, Ellbogen nach außen führen und Hände neben die Ohren ziehen. Nicht nach unten ziehen und nicht ins Hohlkreuz fallen.</div>`; if(name === "Farmer Carry") return `<div class="note"><b>Farmer Carry:</b> Als Strecke/Zeit ausführen: 30 m oder ca. 45 Sek. Aufrecht bleiben, Schultern ruhig, Rumpf fest.</div>`; return ""; }
function setRows(ex, wi, ei){ const sets = parseInt(ex[1], 10) || 3; const target = ex[2]; return `<table class="set-table"><tr><th>Satz</th><th>Ziel</th><th>Gewicht</th><th>Wdh.</th><th>RPE</th><th>✓</th></tr>${Array.from({length:sets}).map((_,si) => `<tr><td>${si+1}</td><td>${target}</td><td><input type="text" data-id="set_w_${wi}_${ei}_${si}" placeholder="kg"></td><td><input type="text" data-id="set_r_${wi}_${ei}_${si}" placeholder="Ist"></td><td><input type="text" data-id="set_p_${wi}_${ei}_${si}" placeholder="RPE"></td><td><input type="checkbox" data-id="set_d_${wi}_${ei}_${si}"></td></tr>`).join("")}</table>`; }
function renderWorkouts(){ $("workoutContainer").innerHTML = D.workouts.map((workout,wi) => `<div class="card"><h2>${workout.title}</h2><div class="grid"><div class="metric"><span>Dauer</span>${workout.duration}</div><div class="metric"><span>Fokus</span>${workout.focus}</div></div>${renderWarmup(workout, wi)}${rpeBox()}<div class="note"><b>Technik-Cues:</b> ${workout.cues}</div>${workout.exercises.map((ex,ei) => `<div class="exercise-card"><div class="exercise-head"><span class="exercise-title">${ex[0]}</span><label><input type="checkbox" data-id="ex_done_${wi}_${ei}"> erledigt</label></div><div class="reference-bar"><b>Referenz Vorwoche</b><br>Ab Woche 2: Gewicht · Wiederholungen · RPE aus der Vorwoche.</div><div class="image-placeholder">Übungsbild: ${ex[0]}<br><span class="small">Platzhalter für Illustration</span></div><div class="exercise-meta"><div><b>${ex[1]}</b>Sätze</div><div><b>${ex[2]}</b>Ziel-Wdh.</div><div><b>${ex[3]}</b>Pause</div><div><b>${ex[5]}</b>Ziel-RPE</div></div>${specialNote(ex[0])}${setRows(ex, wi, ei)}<textarea rows="2" data-id="ex_note_${wi}_${ei}" placeholder="Notizen"></textarea></div>`).join("")}<h3>Training heute</h3><div class="grid"><input type="text" data-id="duration_${wi}" placeholder="Trainingsdauer"><input type="text" data-id="avg_rpe_${wi}" placeholder="Ø RPE"></div><label class="item"><input type="checkbox" data-id="increase_${wi}">Nächstes Training Gewicht erhöhen?</label></div>`).join(""); }
function renderRecipes(list = D.recipes){ $("recipeContainer").innerHTML = list.map(recipe => { const i = D.recipes.indexOf(recipe); return `<div class="recipe-card" id="recipe-${i}"><div class="recipe-head"><h2>Rezept ${i+1}</h2><span class="badge">${recipe[2]}</span></div><h3>${recipe[0]}</h3><div class="grid"><div class="pill">${recipe[1]}</div><div class="pill">${recipe[3]}</div><div class="pill">${recipe[7]}</div></div><h4>Zutaten</h4><ul>${recipe[4].map(z => `<li>${z}</li>`).join("")}</ul><h4>Zubereitung</h4><p>${recipe[5]}</p><h4>Nährwerte</h4><p class="pill">${recipe[6]}</p><h4>Kinderfreundlich</h4><p class="small">Mild würzen, Komponenten bei Bedarf getrennt servieren.</p></div>`; }).join(""); }
function renderShopping(){ $("shopContainer").innerHTML = Object.entries(D.shopCats).map(([category,items],ci) => `<h3>${category}</h3>${items.map((item,ii) => `<label class="item"><input type="checkbox" data-id="shop_${ci}_${ii}"><span>${item}</span></label>`).join("")}`).join(""); }
function filterRecipes(){ const input = $("recipeSearch"); if(!input) return; const q = input.value.toLowerCase().trim(); const filtered = D.recipes.filter(r => (r[0] + " " + r[3] + " " + r[7] + " " + r[4].join(" ")).toLowerCase().includes(q)); renderRecipes(filtered); }
document.addEventListener("DOMContentLoaded", () => { renderDays(); renderWorkouts(); renderRecipes(); renderShopping(); restore(); document.querySelectorAll("[data-screen]").forEach(button => { button.addEventListener("click", () => showScreen(button.dataset.screen)); }); document.addEventListener("input", e => { save(e.target); if(e.target.id === "recipeSearch") filterRecipes(); }); document.addEventListener("change", e => save(e.target)); if("serviceWorker" in navigator){ navigator.serviceWorker.register("./service-worker.js").catch(() => {}); } });
