
window.WEEK1={days:[
{name:"Montag",focus:"Unterkörper",info:"Training ca. 60 Min. · Protein 120–150 g",meals:[["07:00","Frühstück","Proteinbrot mit Tilsiter & Gemüse","recipe-0","430 kcal · 31 g Protein"],["12:30","Mittag","Linsen-Feta-Salat","recipe-2","Rezept 3"],["17:30","Abend","Familien-Linsen-Bolognese","recipe-3","Rezept 4"]]},
{name:"Dienstag",focus:"Mobility",info:"10–15 Min. Mobility",meals:[["07:00","Frühstück","Protein-Porridge","recipe-1","Rezept 2"],["12:30","Mittag","Linsen-Feta-Salat","recipe-2","Rezept 3"],["17:30","Abend","Familien-Linsen-Bolognese","recipe-3","Rezept 4"]]},
{name:"Mittwoch",focus:"Alltagsbewegung",info:"30–45 Min. Spaziergang",meals:[["07:00","Frühstück","Overnight Oats","",""],["12:30","Mittag","Couscous-Feta-Salat","recipe-4","Rezept 5"],["17:30","Abend","Abendessen außer Haus","",""]]},
{name:"Donnerstag",focus:"Oberkörper",info:"Training ca. 60 Min.",meals:[["07:00","Frühstück","Proteinbrot mit Tilsiter & Gemüse","recipe-0","Rezept 1"],["12:30","Mittag","Couscous-Feta-Salat","recipe-4","Rezept 5"],["17:30","Abend","Mildes Kichererbsencurry","recipe-5","Rezept 6"]]},
{name:"Freitag",focus:"Mobility",info:"10–15 Min. Mobility",meals:[["07:00","Frühstück","Overnight Oats","",""],["12:30","Mittag","Burrito Bowl","recipe-6","Rezept 7"],["17:30","Abend","Mildes Kichererbsencurry","recipe-5","Rezept 6"]]},
{name:"Samstag",focus:"Ganzkörper",info:"Training ca. 60 Min.",meals:[["08:00","Frühstück","Protein-Porridge","recipe-1","Rezept 2"],["13:00","Mittag","Tofu-Reispfanne","recipe-7","Eva + Janis"],["18:00","Abend","Tofu-Reispfanne","recipe-7","Familie"]]},
{name:"Sonntag",focus:"Meal Prep",info:"Vorbereitung auf Woche 2",meals:[["08:00","Frühstück","Proteinbrot mit Tilsiter & Gemüse","recipe-0","Rezept 1"],["13:00","Mittag","Kartoffel-Brokkoli-Auflauf","recipe-8","Eva + Janis"],["18:00","Abend","Kartoffel-Brokkoli-Auflauf","recipe-8","Familie"]]}],
workouts:[
{title:"Montag · Unterkörper",duration:"ca. 60 Min.",focus:"Gesäß · Beine · Core",cues:"Rumpf aktiv anspannen · Knie folgen der Fußrichtung · volle Bewegungsamplitude",warmup:{cardio:["Laufband 5 Min.","Fahrrad 5 Min.","Crosstrainer 5 Min."],mobility:["Hüftkreisen ×10","Beinpendeln ×10 je Seite","Cat-Cow ×8"],activation:["Glute Bridge ×12","Bodyweight Squats ×10","Monster Walk optional"]},exercises:[["Kniebeuge","4","8","60–90 Sek.","3–1–1","7"],["Hip Thrust","4","10","60–90 Sek.","2–1–2","7"],["Rumänisches Kreuzheben","3","10","60–90 Sek.","3–1–1","7"],["Bulgarian Split Squat","3","10 je Seite","45–60 Sek.","2–1–2","8"],["Abduktion","3","15","30–45 Sek.","2–1–2","8"],["Wadenheben","3","15","30–45 Sek.","2–1–2","8"],["Dead Bug","3","10 je Seite","30–45 Sek.","kontrolliert","–"],["Pallof Press","3","12 je Seite","30–45 Sek.","kontrolliert","–"]]},
{title:"Donnerstag · Oberkörper",duration:"ca. 60 Min.",focus:"Rücken · Schultern · Arme · Core",cues:"Schulterblätter aktiv · Brustkorb aufrichten · Rumpf stabil",warmup:{cardio:["Rudergerät 5 Min.","Crosstrainer 5 Min.","SkiErg 5 Min."],mobility:["Armkreisen ×10","Thorax-Rotation ×8 je Seite","Schulterkreisen ×10"],activation:["Band Pull Apart ×12","Face Pull mit Band ×12","Außenrotation Band ×10 je Seite"]},exercises:[["Latzug","4","10","45–60 Sek.","2–1–2","7"],["Sitzendes Rudern","4","10","45–60 Sek.","2–1–2","7"],["Schulterdrücken","3","10","45–60 Sek.","2–1–2","7"],["Seitheben","3","15","30–45 Sek.","2–1–2","8"],["Face Pull","3","15","30–45 Sek.","2–1–2","8"],["Bizepscurls","3","12","30–45 Sek.","2–1–2","8"],["Trizepsdrücken","3","12","30–45 Sek.","2–1–2","8"],["Bird Dog","3","10 je Seite","30–45 Sek.","kontrolliert","–"]]},
{title:"Samstag · Ganzkörper",duration:"ca. 60 Min.",focus:"Ganzkörper · Stabilität · Kraft",cues:"Qualität vor Gewicht · Rumpf stabil · kontrollierte Bewegung",warmup:{cardio:["Laufband 5 Min.","Rudergerät 5 Min.","Fahrrad 5 Min."],mobility:["Cat-Cow ×8","Hüftkreisen ×10","Armkreisen ×10"],activation:["Glute Bridge ×10","Band Pull Apart ×12","Bodyweight Squats ×10"]},exercises:[["Kreuzheben","4","6","60–90 Sek.","3–1–1","7"],["Beinpresse","3","10","45–60 Sek.","2–1–2","7"],["Schrägbankdrücken","3","10","45–60 Sek.","2–1–2","7"],["Latzug enger Griff","3","10","45–60 Sek.","2–1–2","7"],["Hip Thrust","3","12","45–60 Sek.","2–1–2","8"],["Face Pull","3","15","30–45 Sek.","2–1–2","8"],["Farmer Carry","3","30 m oder 45 Sek.","45–60 Sek.","kontrolliert","7"],["Pallof Press","3","12 je Seite","30–45 Sek.","kontrolliert","–"]]}],
recipes:[
["Proteinbrot mit Tilsiter & Gemüse","5 Minuten","1 Portion","Montag, Donnerstag, Sonntag Frühstück",["2 Scheiben Proteinbrot","60 g Tilsiter","½ rote Paprika","⅓ Gurke","6–8 Cherrytomaten"],"Gemüse waschen, Brot mit Tilsiter belegen und frisch servieren.","430 kcal · 31 g Protein · 29 g KH · 18 g Fett","Frühstück"],
["Protein-Porridge","10 Minuten","1 Portion","Dienstag, Samstag",["60 g Haferflocken","250 ml Milch","30 g Proteinpulver","100 g TK-Beeren","10 g Chiasamen"],"Haferflocken mit Milch aufkochen, Proteinpulver einrühren, Beeren und Chiasamen ergänzen.","500 kcal · 40 g Protein · 49 g KH · 11 g Fett","Frühstück"],
["Linsen-Feta-Salat","20 Minuten","4 Portionen","Montag & Dienstag Mittag",["300 g rote Linsen","200 g Feta","1 Gurke","2 Paprika","250 g Cherrytomaten","1 rote Zwiebel","3 EL Olivenöl","Petersilie","Zitronensaft"],"Linsen garen, Gemüse würfeln, Feta zerbröseln, alles vermengen.","510 kcal · 28 g Protein · 46 g KH · 21 g Fett","Meal Prep"],
["Familien-Linsen-Bolognese","35 Minuten","8 Portionen","Montag & Dienstag Abend",["500 g rote Linsen","800 g Vollkornnudeln","2 Packungen passierte Tomaten","2 Zwiebeln","3 Möhren","2 Zucchini","3 Knoblauchzehen","2 EL Tomatenmark"],"Gemüse würfeln, anschwitzen, Linsen und Tomaten zugeben, köcheln lassen, Nudeln separat kochen.","620 kcal · 31 g Protein · 82 g KH · 14 g Fett","Familie"],
["Couscous-Feta-Salat","15 Minuten","4 Portionen","Mittwoch & Donnerstag Mittag",["250 g Couscous","200 g Feta","1 Gurke","2 Paprika","250 g Cherrytomaten","Petersilie","Zitronensaft","2 EL Olivenöl"],"Couscous quellen lassen, Gemüse schneiden, Feta ergänzen, abschmecken.","490 kcal · 24 g Protein · 47 g KH · 20 g Fett","Meal Prep"],
["Mildes Kichererbsencurry","30 Minuten","8 Portionen","Donnerstag & Freitag Abend",["4 Dosen Kichererbsen","2 Dosen Kokosmilch","2 Brokkoli","2 Paprika","2 Zwiebeln","2 EL milde Currypaste","500 g Basmatireis"],"Reis kochen. Gemüse anbraten, Currypaste, Kokosmilch und Kichererbsen zugeben, köcheln lassen.","610 kcal · 22 g Protein · 72 g KH · 21 g Fett","Familie"],
["Burrito Bowl","20 Minuten","2 Portionen","Freitag Mittag",["200 g Basmatireis","200 g Räuchertofu","1 Paprika","1 Dose Kidneybohnen","1 kleine Dose Mais","½ Avocado","Limettensaft"],"Reis kochen, Tofu anbraten, alles als Bowl anrichten. Avocado frisch ergänzen.","670 kcal · 33 g Protein · 67 g KH · 24 g Fett","Mittag"],
["Tofu-Reispfanne","25 Minuten","6 Portionen","Samstag Mittag Eva + Janis, Samstag Abend Familie",["400 g Räuchertofu","450 g Basmatireis","2 Brokkoli","2 Paprika","2 Zucchini","2 Knoblauchzehen","3 EL Sojasauce","1 EL Sesam"],"Reis kochen, Tofu anbraten, Gemüse garen, alles mit Sojasauce vermengen.","560 kcal · 27 g Protein · 59 g KH · 17 g Fett","Familie"],
["Kartoffel-Brokkoli-Auflauf","40 Minuten","6 Portionen","Sonntag Mittag Eva + Janis, Sonntag Abend Familie",["1,5 kg Kartoffeln","2 Brokkoli","300 ml Kochsahne","250 g geriebener Tilsiter","Muskat","Salz","Pfeffer"],"Kartoffeln schneiden, Brokkoli vorgaren, schichten, Sahne und Käse ergänzen, 35–40 Min. bei 180 °C backen.","540 kcal · 24 g Protein · 49 g KH · 22 g Fett","Familie"]],
shopCats:{"Gemüse":["10 Paprika","4 Gurken","700 g Cherrytomaten","4 Brokkoli","4 Zucchini","1 Beutel Möhren","1 Netz Zwiebeln","1 Knolle Knoblauch","2 kg Kartoffeln","1 Bund Petersilie","1 Zitrone","1 Limette","1 Avocado"],"Obst":["1 Beutel Äpfel","1 Bund Bananen","750 g TK-Beeren"],"Milchprodukte":["1 Packung Tilsiter (500–600 g)","2 Packungen Feta","2 Becher Skyr","2 Becher Hüttenkäse","1 Liter Milch","1 Becher Kochsahne"],"Vorrat & Protein":["1 kg rote Linsen","4 Dosen Kichererbsen","1 Dose Kidneybohnen","1 kleine Dose Mais","Proteinbrot","Vollkornnudeln","1,5 kg Basmatireis","Couscous","Haferflocken","Linsenwaffeln","3 Packungen Räuchertofu","Proteinpulver"],"Sonstiges":["Passierte Tomaten","Tomatenmark","Olivenöl","Kokosmilch","milde Currypaste","Sojasauce","Chiasamen","Walnüsse","Mandelmus","Sesam","Italienische Kräuter","Muskat","Salz","Pfeffer"]}
};
