
window.WEEK1={
days:[
{name:"Montag",focus:"Unterkörper",type:"training",info:"Training 70–75 Min. · Protein 120–150 g · Wasser 2–3 L",meals:[["07:00","Frühstück","Proteinbrot mit Tilsiter & Gemüse","430 kcal · 31 g Protein"],["10:00","Snack","Skyr mit TK-Beeren & Walnüssen","proteinreich"],["12:30","Mittag","Linsen-Feta-Salat","Rezept 3"],["15:30","Snack","150 g Hüttenkäse mit Paprikastreifen","ca. 20 g Protein"],["17:30","Abend","Familien-Linsen-Bolognese","Rezept 4"],["21:00","Optional","Proteinshake","nur falls Proteinziel offen"]]},
{name:"Dienstag",focus:"Regeneration & Mobility",type:"mobility",info:"10–15 Min. Mobility · Protein 120–150 g",meals:[["07:00","Frühstück","Protein-Porridge","Rezept 2"],["10:00","Snack","Skyr mit TK-Beeren",""],["12:30","Mittag","Linsen-Feta-Salat","Rezept 3"],["15:30","Snack","Edamame mit Meersalz",""],["17:30","Abend","Familien-Linsen-Bolognese","Rezept 4"],["20:30","Optional","Naturjoghurt mit Zimt","falls Proteinziel offen"]]},
{name:"Mittwoch",focus:"Alltagsbewegung",type:"recovery",info:"30–45 Min. Spaziergang · Abendessen außer Haus",meals:[["07:00","Frühstück","Overnight Oats",""],["10:00","Snack","Hüttenkäse mit Gurkenscheiben",""],["12:30","Mittag","Couscous-Feta-Salat","Rezept 5"],["15:30","Snack","Apfel mit Mandelmus",""],["17:30","Abend","Abendessen außer Haus",""],["20:30","Optional","Proteinshake","bei proteinarmem Abendessen"]]},
{name:"Donnerstag",focus:"Oberkörper",type:"training",info:"Training 70–75 Min. · Protein 120–150 g",meals:[["07:00","Frühstück","Proteinbrot mit Tilsiter & Gemüse","Rezept 1"],["10:00","Snack","Skyr mit TK-Beeren",""],["12:30","Mittag","Couscous-Feta-Salat","Rezept 5"],["15:30","Snack","150 g Hüttenkäse mit Paprikastreifen",""],["17:30","Abend","Mildes Kichererbsencurry","Rezept 6"],["21:00","Optional","Proteinshake","nur falls Proteinziel offen"]]},
{name:"Freitag",focus:"Regeneration & Mobility",type:"mobility",info:"10–15 Min. Mobility · Vorbereitung auf Samstag",meals:[["07:00","Frühstück","Overnight Oats",""],["10:00","Snack","Skyr mit TK-Beeren",""],["12:30","Mittag","Burrito Bowl","Rezept 7"],["15:30","Snack","150 g Hüttenkäse mit Gurkensticks",""],["17:30","Abend","Mildes Kichererbsencurry","Rezept 6"],["20:30","Optional","Naturjoghurt mit Zimt","falls Proteinziel offen"]]},
{name:"Samstag",focus:"Ganzkörper",type:"training",info:"Training 75 Min. · Schritte 8.000+",meals:[["08:00","Frühstück","Protein-Porridge","Rezept 2"],["10:30","Snack","Skyr mit TK-Beeren",""],["13:00","Mittag","Tofu-Reispfanne","2 Portionen – Eva + Janis"],["16:00","Snack","Edamame mit Meersalz",""],["18:00","Abend","Tofu-Reispfanne","4 Portionen – Familie"],["20:30","Optional","Proteinshake","nur falls Proteinziel offen"]]},
{name:"Sonntag",focus:"Meal Prep & Wochenreview",type:"prep",info:"Vorbereitung auf Woche 2",meals:[["08:00","Frühstück","Proteinbrot mit Tilsiter & Gemüse","Rezept 1"],["10:30","Snack","Skyr mit TK-Beeren",""],["13:00","Mittag","Kartoffel-Brokkoli-Auflauf","2 Portionen – Eva + Janis"],["16:00","Snack","Apfel mit Mandelmus",""],["18:00","Abend","Kartoffel-Brokkoli-Auflauf","4 Portionen – Familie"]]}
],
workouts:[
{title:"Montag · Unterkörper",focus:"Gesäß · Beine · Core",cues:"Rumpf aktiv anspannen · Knie folgen der Fußrichtung · volle Bewegungsamplitude",exercises:[["Kniebeuge","4","8","90–120 Sek.","3–1–1","7"],["Hip Thrust","4","10","90 Sek.","2–1–2","7"],["Rumänisches Kreuzheben","3","10","90 Sek.","3–1–1","7"],["Bulgarian Split Squat","3","10 je Seite","60–90 Sek.","2–1–2","8"],["Abduktion","3","15","45–60 Sek.","2–1–2","8"],["Wadenheben","3","15","45–60 Sek.","2–1–2","8"],["Dead Bug","3","10 je Seite","30 Sek.","kontrolliert","–"],["Pallof Press","3","12 je Seite","30 Sek.","kontrolliert","–"]]},
{title:"Donnerstag · Oberkörper",focus:"Rücken · Schultern · Arme · Core",cues:"Schulterblätter aktiv · Brustkorb aufrichten · Rumpf stabil",exercises:[["Latzug","4","10","90 Sek.","2–1–2","7"],["Sitzendes Rudern","4","10","90 Sek.","2–1–2","7"],["Schulterdrücken","3","10","90 Sek.","2–1–2","7"],["Seitheben","3","15","60 Sek.","2–1–2","8"],["Face Pull","3","15","60 Sek.","2–1–2","8"],["Bizepscurls","3","12","60 Sek.","2–1–2","8"],["Trizepsdrücken","3","12","60 Sek.","2–1–2","8"],["Bird Dog","3","10 je Seite","30 Sek.","kontrolliert","–"]]},
{title:"Samstag · Ganzkörper",focus:"Ganzkörper · Stabilität · Kraft",cues:"Qualität vor Gewicht · Rumpf stabil · kontrollierte Bewegung",exercises:[["Kreuzheben","4","6","120 Sek.","3–1–1","7"],["Beinpresse","3","10","90 Sek.","2–1–2","7"],["Schrägbankdrücken","3","10","90 Sek.","2–1–2","7"],["Latzug enger Griff","3","10","90 Sek.","2–1–2","7"],["Hip Thrust","3","12","90 Sek.","2–1–2","8"],["Face Pull","3","15","60 Sek.","2–1–2","8"],["Farmer Carry","3","30 m","60 Sek.","kontrolliert","7"],["Pallof Press","3","12 je Seite","30 Sek.","kontrolliert","–"]]}
],
recipes:[
["Proteinbrot mit Tilsiter & Gemüse","5 Minuten","1 Portion","Montag, Donnerstag, Sonntag Frühstück",["2 Scheiben Proteinbrot","60 g Tilsiter","½ rote Paprika","⅓ Gurke","6–8 Cherrytomaten"],"Gemüse waschen, Brot mit Tilsiter belegen und frisch servieren.","430 kcal · 31 g Protein · 29 g KH · 18 g Fett"],
["Protein-Porridge","10 Minuten","1 Portion","Dienstag, Samstag",["60 g Haferflocken","250 ml Milch","30 g Proteinpulver","100 g TK-Beeren","10 g Chiasamen"],"Haferflocken mit Milch aufkochen, Proteinpulver einrühren, Beeren und Chiasamen ergänzen.","500 kcal · 40 g Protein · 49 g KH · 11 g Fett"],
["Linsen-Feta-Salat","20 Minuten","4 Portionen","Montag & Dienstag Mittag",["300 g rote Linsen","200 g Feta","1 Gurke","2 Paprika","250 g Cherrytomaten","1 rote Zwiebel","3 EL Olivenöl","Petersilie","Zitronensaft"],"Linsen garen, Gemüse würfeln, Feta zerbröseln, alles vermengen.","510 kcal · 28 g Protein · 46 g KH · 21 g Fett"],
["Familien-Linsen-Bolognese","35 Minuten","8 Portionen","Montag & Dienstag Abend",["500 g rote Linsen","800 g Vollkornnudeln","2 Packungen passierte Tomaten","2 Zwiebeln","3 Möhren","2 Zucchini","3 Knoblauchzehen","2 EL Tomatenmark"],"Gemüse würfeln, anschwitzen, Linsen und Tomaten zugeben, köcheln lassen, Nudeln separat kochen.","620 kcal · 31 g Protein · 82 g KH · 14 g Fett"],
["Couscous-Feta-Salat","15 Minuten","4 Portionen","Mittwoch & Donnerstag Mittag",["250 g Couscous","200 g Feta","1 Gurke","2 Paprika","250 g Cherrytomaten","Petersilie","Zitronensaft","2 EL Olivenöl"],"Couscous quellen lassen, Gemüse schneiden, Feta ergänzen, abschmecken.","490 kcal · 24 g Protein · 47 g KH · 20 g Fett"],
["Mildes Kichererbsencurry","30 Minuten","8 Portionen","Donnerstag & Freitag Abend",["4 Dosen Kichererbsen","2 Dosen Kokosmilch","2 Brokkoli","2 Paprika","2 Zwiebeln","2 EL milde Currypaste","500 g Basmatireis"],"Reis kochen. Gemüse anbraten, Currypaste, Kokosmilch und Kichererbsen zugeben, köcheln lassen.","610 kcal · 22 g Protein · 72 g KH · 21 g Fett"],
["Burrito Bowl","20 Minuten","2 Portionen","Freitag Mittag",["200 g Basmatireis","200 g Räuchertofu","1 Paprika","1 Dose Kidneybohnen","1 kleine Dose Mais","½ Avocado","Limettensaft"],"Reis kochen, Tofu anbraten, alles als Bowl anrichten. Avocado frisch ergänzen.","670 kcal · 33 g Protein · 67 g KH · 24 g Fett"],
["Tofu-Reispfanne","25 Minuten","6 Portionen","Samstag Mittag Eva + Janis, Samstag Abend Familie",["400 g Räuchertofu","450 g Basmatireis","2 Brokkoli","2 Paprika","2 Zucchini","2 Knoblauchzehen","3 EL Sojasauce","1 EL Sesam"],"Reis kochen, Tofu anbraten, Gemüse garen, alles mit Sojasauce vermengen.","560 kcal · 27 g Protein · 59 g KH · 17 g Fett"],
["Kartoffel-Brokkoli-Auflauf","40 Minuten","6 Portionen","Sonntag Mittag Eva + Janis, Sonntag Abend Familie",["1,5 kg Kartoffeln","2 Brokkoli","300 ml Kochsahne","250 g geriebener Tilsiter","Muskat","Salz","Pfeffer"],"Kartoffeln schneiden, Brokkoli vorgaren, schichten, Sahne und Käse ergänzen, 35–40 Min. bei 180 °C backen.","540 kcal · 24 g Protein · 49 g KH · 22 g Fett"]
],
shopCats:{"Gemüse":["10 Paprika","4 Gurken","700 g Cherrytomaten","4 Brokkoli","4 Zucchini","1 Beutel Möhren","1 Netz Zwiebeln","1 Knolle Knoblauch","2 kg Kartoffeln","1 Bund Petersilie","1 Zitrone","1 Limette","1 Avocado"],"Obst":["1 Beutel Äpfel","1 Bund Bananen","750 g TK-Beeren"],"Milchprodukte":["1 Packung Tilsiter (500–600 g)","2 Packungen Feta","2 Becher Skyr","2 Becher Hüttenkäse","1 Liter Milch","1 Becher Kochsahne"],"Vorrat & Protein":["1 kg rote Linsen","4 Dosen Kichererbsen","1 Dose Kidneybohnen","1 kleine Dose Mais","Proteinbrot","Vollkornnudeln","1,5 kg Basmatireis","Couscous","Haferflocken","Linsenwaffeln","3 Packungen Räuchertofu","Proteinpulver"],"Sonstiges":["Passierte Tomaten","Tomatenmark","Olivenöl","Kokosmilch","milde Currypaste","Sojasauce","Chiasamen","Walnüsse","Mandelmus","Sesam","Italienische Kräuter","Muskat","Salz","Pfeffer"]}
};
